# Generated by Django 4.0.5 on 2022-06-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="published",),
        migrations.AlterField(
            model_name="author",
            name="initials",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="book", name="blurb", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(null=True, to="books.genre"),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="book", name="page_count", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="pub_date",
            field=models.DateField(null=True, verbose_name="published date"),
        ),
        migrations.AlterField(
            model_name="book",
            name="subtitle",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="reading", name="comments", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="reading",
            name="finished_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="reading", name="rating", field=models.FloatField(null=True),
        ),
    ]
